spring:
  application:
    name: inmo

  datasource:
    url: jdbc:postgresql://localhost:5432/easyprop
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true
    locations: classpath:db/migration